// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Image from './Image';
import Lead from './Lead';
import Quote from './Quote';
import Solutions from './Solutions';
import Team from './Team';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';
import WhatWeDo from './WhatWeDo';

export {
	Hero,
	Image,
	Lead,
	Quote,
	Solutions,
	Team,
	TextWithFeatures,
	TextWithImage,
	WhatWeDo,
};

export const components = {
	hero: Hero,
	image: Image,
	lead: Lead,
	quote: Quote,
	solutions: Solutions,
	team: Team,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
	what_we_do: WhatWeDo,
};
